// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        int64              `json:"id"`
	Owner     string             `json:"owner"`
	Balance   int64              `json:"balance"`
	Currency  string             `json:"currency"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Brand struct {
	ID           int32       `json:"id"`
	Title        string      `json:"title"`
	InfoTableID  pgtype.Int4 `json:"info_table_id"`
	EnterpriseID pgtype.Int4 `json:"enterprise_id"`
}

type Enterprise struct {
	ID                   int32       `json:"id"`
	Title                string      `json:"title"`
	DocumentVerification string      `json:"document_verification"`
	Phone                string      `json:"phone"`
	Email                string      `json:"email"`
	Contact              pgtype.Text `json:"contact"`
	ContactPhone         string      `json:"contact_phone"`
	Files                string      `json:"files"`
	Address              string      `json:"address"`
	Web                  string      `json:"web"`
	IsAuthenticated      bool        `json:"is_authenticated"`
	InfoTableID          pgtype.Int4 `json:"info_table_id"`
}

type Entry struct {
	ID        int64 `json:"id"`
	AccountID int64 `json:"account_id"`
	// can be negative or positive
	Amount    int64              `json:"amount"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type InfoTable struct {
	ID        int32              `json:"id"`
	Status    string             `json:"status"`
	Removable bool               `json:"removable"`
	Editable  bool               `json:"editable"`
	IsVisible bool               `json:"is_visible"`
	Default   bool               `json:"default"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	CreatedBy pgtype.Text        `json:"created_by"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy pgtype.Text        `json:"updated_by"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy pgtype.Text        `json:"deleted_by"`
}

type Transfer struct {
	ID            int64 `json:"id"`
	FromAccountID int64 `json:"from_account_id"`
	ToAccountID   int64 `json:"to_account_id"`
	// must be positive
	Amount    int64              `json:"amount"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID                int32              `json:"id"`
	IsAuthenticated   bool               `json:"is_authenticated"`
	Email             string             `json:"email"`
	Password          string             `json:"password"`
	Phone             pgtype.Text        `json:"phone"`
	FullName          string             `json:"full_name"`
	Username          string             `json:"username"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	InfoTableID       pgtype.Int4        `json:"info_table_id"`
	EnterpriseID      pgtype.Int4        `json:"enterprise_id"`
}
